---
- hosts: localhost
  tasks: 
  - name: Change file ownership, group and permissions
    file:
      path: file1.java  
      owner: ec2-user
      group: ec2-user
      mode: '0644'
      state: touch

        
